//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Menus.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
        TButton *Button1;
        TButton *Button2;
        TLabel *Wisielec;
        TButton *Button3;
        TLabel *Label1;
        TButton *Button4;
        TButton *Button5;
        TMainMenu *MainMenu1;
        TMenuItem *Opjce1;
        TMenuItem *Nowagra1;
        TMenuItem *Zakocz1;
        TImage *Image1;
        TImage *Image11;
        TImage *Image12;
        TImage *Image13;
        TImage *Image14;
        TImage *Image15;
        TImage *Image16;
        TImage *Image17;
        TImage *Image18;
        TImage *Image19;
        TImage *Image20;
        TImage *Image21;
        TImage *Image22;
        TImage *Image23;
        TImage *Image24;
        TImage *Image25;
        TImage *Image26;
        TImage *Image27;
        TImage *Image28;
        TImage *Image29;
        TImage *Image30;
        TImage *Image31;
        TImage *Image32;
        TImage *Image33;
        TImage *Image34;
        TImage *Image35;
        TImage *Image36;
        TImage *Image37;
        TImage *Image38;
        TImage *Image39;
        TImage *Image40;
        TImage *Image41;
        TImage *Image42;
        TImage *Image43;
        TImage *Image44;
        TImage *Image45;
        TLabel *Label2;
        TLabel *pytanieI;
        TLabel *pytanieII;
        TButton *Button6;
        TLabel *ZgadujPierwszy;
        TLabel *ZgadujDrugi;
        TImage *Image46;
        TImage *Image47;
        TImage *Image48;
        TImage *Image49;
        TImage *Image50;
        TImage *Image51;
        TImage *Image52;
        TImage *Image53;
        TImage *Image54;
        TImage *Image55;
        TImage *Image56;
        TImage *Image57;
        TImage *Image58;
        TImage *Image59;
        TImage *Image60;
        TImage *Image61;
        TImage *Image62;
        TImage *Image63;
        TImage *Image64;
        TImage *Image65;
        TImage *Image66;
        TImage *Image67;
        TImage *Image68;
        TImage *Image69;
        TImage *Image70;
        TImage *Image71;
        TImage *Image72;
        TImage *Image73;
        TImage *Image74;
        TImage *Image75;
        TImage *Image76;
        TImage *Image77;
        TImage *Image78;
        TImage *Image79;
        TImage *Image80;
        TLabel *Label3;
        TImage *Image2;
        TButton *Button7;
        TLabel *Label4;
        TImage *Image108;
        TImage *Image109;
        TImage *Image110;
        TImage *Image111;
        TImage *Image112;
        TImage *Image113;
        TImage *Image114;
        TImage *Image115;
        TImage *Image116;
        TImage *Image117;
        TImage *Image118;
        TImage *Image119;
        TImage *Image120;
        TImage *Image121;
        TImage *Image122;
        TImage *Image123;
        TImage *Image124;
        TImage *Image125;
        TImage *Image126;
        TImage *Image127;
        TImage *Image128;
        TImage *Image129;
        TImage *Image130;
        TImage *Image131;
        TImage *Image132;
        TImage *Image133;
        TImage *Image134;
        TImage *Image135;
        TImage *Image136;
        TImage *Image137;
        TImage *Image138;
        TImage *Image139;
        TImage *Image140;
        TImage *Image141;
        TImage *Image142;
        TLabel *Label5;
        TButton *Button8;
        TLabel *Label6;
        TLabel *Label7;
        TButton *Button9;
        TLabel *Label8;
        TLabel *Label9;
        TLabel *Label10;
        void __fastcall Button3Click(TObject *Sender);
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall Zakocz1Click(TObject *Sender);
        void __fastcall Button2Click(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall Button4Click(TObject *Sender);
        void __fastcall Button5Click(TObject *Sender);
        void __fastcall Image23Click(TObject *Sender);
        void __fastcall Image24Click(TObject *Sender);
        void __fastcall Image26Click(TObject *Sender);
        void __fastcall Image27Click(TObject *Sender);
        void __fastcall Image32Click(TObject *Sender);
        void __fastcall Image31Click(TObject *Sender);
        void __fastcall Image30Click(TObject *Sender);
        void __fastcall Image29Click(TObject *Sender);
        void __fastcall Image28Click(TObject *Sender);
        void __fastcall Image33Click(TObject *Sender);
        void __fastcall Image34Click(TObject *Sender);
        void __fastcall Image35Click(TObject *Sender);
        void __fastcall Imag36Click(TObject *Sender);
        void __fastcall Image37Click(TObject *Sender);
        void __fastcall Image38Click(TObject *Sender);
        void __fastcall Image39Click(TObject *Sender);
        void __fastcall Image44Click(TObject *Sender);
        void __fastcall Image43Click(TObject *Sender);
        void __fastcall Image42Click(TObject *Sender);
        void __fastcall Image41Click(TObject *Sender);
        void __fastcall Image40Click(TObject *Sender);
        void __fastcall Image45Click(TObject *Sender);
        void __fastcall Image25Click(TObject *Sender);
        void __fastcall Button6Click(TObject *Sender);
        void __fastcall Image58Click(TObject *Sender);
        void __fastcall Image59Click(TObject *Sender);
        void __fastcall Image60Click(TObject *Sender);
        void __fastcall Image61Click(TObject *Sender);
        void __fastcall Image62Click(TObject *Sender);
        void __fastcall Image63Click(TObject *Sender);
        void __fastcall Image64Click(TObject *Sender);
        void __fastcall Image65Click(TObject *Sender);
        void __fastcall Image66Click(TObject *Sender);
        void __fastcall Image67Click(TObject *Sender);
        void __fastcall Image68Click(TObject *Sender);
        void __fastcall Image69Click(TObject *Sender);
        void __fastcall Image70Click(TObject *Sender);
        void __fastcall Image71Click(TObject *Sender);
        void __fastcall Image72Click(TObject *Sender);
        void __fastcall Image73Click(TObject *Sender);
        void __fastcall Image74Click(TObject *Sender);
        void __fastcall Image75Click(TObject *Sender);
        void __fastcall Image76Click(TObject *Sender);
        void __fastcall Image77Click(TObject *Sender);
        void __fastcall Image78Click(TObject *Sender);
        void __fastcall Image79Click(TObject *Sender);
        void __fastcall Image80Click(TObject *Sender);
        void __fastcall Button7Click(TObject *Sender);
        void __fastcall Image120Click(TObject *Sender);
        void __fastcall Button8Click(TObject *Sender);
        void __fastcall Image121Click(TObject *Sender);
        void __fastcall Image122Click(TObject *Sender);
        void __fastcall Image123Click(TObject *Sender);
        void __fastcall Image124Click(TObject *Sender);
        void __fastcall Image125Click(TObject *Sender);
        void __fastcall Image126Click(TObject *Sender);
        void __fastcall Image127Click(TObject *Sender);
        void __fastcall Image128Click(TObject *Sender);
        void __fastcall Image129Click(TObject *Sender);
        void __fastcall Image130Click(TObject *Sender);
        void __fastcall Image131Click(TObject *Sender);
        void __fastcall Image132Click(TObject *Sender);
        void __fastcall Image133Click(TObject *Sender);
        void __fastcall Image134Click(TObject *Sender);
        void __fastcall Image135Click(TObject *Sender);
        void __fastcall Image136Click(TObject *Sender);
        void __fastcall Image137Click(TObject *Sender);
        void __fastcall Image138Click(TObject *Sender);
        void __fastcall Image139Click(TObject *Sender);
        void __fastcall Image140Click(TObject *Sender);
        void __fastcall Image141Click(TObject *Sender);
        void __fastcall Image142Click(TObject *Sender);
        void __fastcall Button9Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
